name: Disable Pages Workflow
on:
  push:
    branches: ["main"]
jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow does nothing to override the default Pages workflow."
